apiVersion: v1
kind: Service
metadata:
  name: srv-demo-service
  namespace: default
spec:
  selector:
    app: srv-demo
  ports:
    - protocol: TCP
      port: 8080       # Porta do serviço Kubernetes
      targetPort: 8080 # Porta do container
      nodePort: 31300  # Porta exposta no cluster (NodePort)
  type: LoadBalancer  # Expondo para acesso externo
