name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          # Username used to log against the Docker registry
          username: 'maxsuelsbr'
          # Password or personal access token used to log against the Docker registry
          password: ${{ DOCKER_PASSWORD }}
              

